#!/usr/bin/env python3
"""
Run a single bot-vs-bot match using the official engine in a fresh run directory.

This runner creates a temporary engine workspace with a generated config.py so
bots can be specified on the command line without editing engine files.
"""
import argparse
import datetime as _dt
import os
import shutil
import subprocess
import sys


def _timestamp_dir(base_dir: str) -> str:
    ts = _dt.datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    candidate = os.path.join(base_dir, ts)
    if not os.path.exists(candidate):
        return candidate
    suffix = 1
    while True:
        candidate = os.path.join(base_dir, "%s_%02d" % (ts, suffix))
        if not os.path.exists(candidate):
            return candidate
        suffix += 1


def _write_config(path: str, args) -> None:
    config_text = """# Auto-generated by tools/run_match.py
PLAYER_1_NAME = "{name_a}"
PLAYER_1_PATH = "{path_a}"
PLAYER_2_NAME = "{name_b}"
PLAYER_2_PATH = "{path_b}"
GAME_LOG_FILENAME = "{gamelog}"
PLAYER_LOG_SIZE_LIMIT = {log_limit}
ENFORCE_GAME_CLOCK = {enforce_clock}
STARTING_GAME_CLOCK = {clock}
BUILD_TIMEOUT = {build_timeout}
CONNECT_TIMEOUT = {connect_timeout}
NUM_ROUNDS = {rounds}
STARTING_STACK = {starting_stack}
BIG_BLIND = {big_blind}
SMALL_BLIND = {small_blind}
PLAYER_TIMEOUT = {player_timeout}
""".format(
        name_a=args.name_a,
        path_a=args.path_a,
        name_b=args.name_b,
        path_b=args.path_b,
        gamelog=args.gamelog_name,
        log_limit=args.player_log_limit,
        enforce_clock=bool(args.enforce_clock),
        clock=args.starting_clock,
        build_timeout=args.build_timeout,
        connect_timeout=args.connect_timeout,
        rounds=args.rounds,
        starting_stack=args.starting_stack,
        big_blind=args.big_blind,
        small_blind=args.small_blind,
        player_timeout=args.player_timeout,
    )
    with open(path, "w") as handle:
        handle.write(config_text)


def _validate_bot_path(path: str) -> None:
    if not os.path.isdir(path):
        raise SystemExit("bot path does not exist: %s" % path)
    commands = os.path.join(path, "commands.json")
    if not os.path.exists(commands):
        raise SystemExit("commands.json not found for bot: %s" % path)


def run() -> int:
    parser = argparse.ArgumentParser(description="Run a single engine match between two bots.")
    parser.add_argument("--engine-dir", default="engine-2026", help="Path to engine directory")
    parser.add_argument("--bot-a", required=True, help="Path to bot A directory")
    parser.add_argument("--bot-b", required=True, help="Path to bot B directory")
    parser.add_argument("--name-a", default="Bot A", help="Display name for bot A")
    parser.add_argument("--name-b", default="Bot B", help="Display name for bot B")
    parser.add_argument("--rounds", type=int, default=1000, help="Number of rounds")
    parser.add_argument("--starting-stack", type=int, default=400, help="Starting stack")
    parser.add_argument("--big-blind", type=int, default=2, help="Big blind")
    parser.add_argument("--small-blind", type=int, default=1, help="Small blind")
    parser.add_argument("--starting-clock", type=float, default=60.0, help="Starting game clock")
    parser.add_argument("--build-timeout", type=float, default=10.0, help="Build timeout")
    parser.add_argument("--connect-timeout", type=float, default=10.0, help="Connect timeout")
    parser.add_argument("--player-timeout", type=float, default=120.0, help="Player timeout")
    parser.add_argument("--player-log-limit", type=int, default=524288, help="Player log size limit")
    parser.add_argument("--gamelog-name", default="gamelog", help="Base name for gamelog")
    parser.add_argument("--output-dir", default="runs", help="Directory to write run outputs")
    parser.add_argument("--seed", type=int, default=None, help="Deterministic seed for the engine RNG")
    parser.add_argument("--engine-python", default=None, help="Python executable for the engine")
    parser.add_argument("--bot-python", default=None, help="Python executable for bot commands")
    parser.add_argument("--enforce-clock", action="store_true", help="Enable game clock")
    parser.add_argument("--no-enforce-clock", dest="enforce_clock", action="store_false")
    parser.set_defaults(enforce_clock=True)
    args = parser.parse_args()

    engine_dir = os.path.abspath(args.engine_dir)
    engine_path = os.path.join(engine_dir, "engine.py")
    if not os.path.exists(engine_path):
        raise SystemExit("engine.py not found in: %s" % engine_dir)

    args.path_a = os.path.abspath(args.bot_a)
    args.path_b = os.path.abspath(args.bot_b)
    _validate_bot_path(args.path_a)
    _validate_bot_path(args.path_b)

    base_dir = os.path.abspath(args.output_dir)
    if not os.path.exists(base_dir):
        os.makedirs(base_dir)
    run_dir = _timestamp_dir(base_dir)
    os.makedirs(run_dir)

    run_engine_path = os.path.join(run_dir, "engine.py")
    run_config_path = os.path.join(run_dir, "config.py")
    shutil.copy2(engine_path, run_engine_path)
    _write_config(run_config_path, args)

    stdout_path = os.path.join(run_dir, "engine_stdout.txt")
    env = os.environ.copy()
    engine_python = args.engine_python or env.get("POKERBOTS_ENGINE_PYTHON") or sys.executable
    bot_python = args.bot_python or env.get("POKERBOTS_BOT_PYTHON")
    if bot_python:
        bot_bin = os.path.dirname(os.path.abspath(bot_python))
        env["PATH"] = bot_bin + os.pathsep + env.get("PATH", "")
    if args.seed is not None:
        env["POKERBOTS_SEED"] = str(args.seed)
    with open(stdout_path, "w") as stdout_handle:
        stdout_handle.write("Engine command: %s %s\n" % (engine_python, run_engine_path))
        stdout_handle.write("Bot A: %s\n" % args.path_a)
        stdout_handle.write("Bot B: %s\n" % args.path_b)
        if args.seed is not None:
            stdout_handle.write("Seed: %s\n" % args.seed)
        stdout_handle.write("\n")
        stdout_handle.flush()
        proc = subprocess.Popen(
            [engine_python, run_engine_path],
            cwd=run_dir,
            env=env,
            stdout=stdout_handle,
            stderr=subprocess.STDOUT,
        )
        return_code = proc.wait()
        stdout_handle.write("\nEngine exit code: %s\n" % return_code)
    return return_code


if __name__ == "__main__":
    raise SystemExit(run())
